stages:
  - building

lbt:
  stage: building
  image: node:14-alpine
  tags:
    - Yellow
  artifacts:
    when: always
    paths:
      - coverage/
    expire_in: 1 week
  script:
    - npm i pnpm -g
    - pnpm i
    - pnpm run lint
    - pnpm run build
    - pnpm run test:cov-html
