stages:
  - building

lbt:
  stage: building
  image: registry.gitlab.com/yellowgarbagegroup/docker-images/node:14-alpine
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .pnpm-store
  artifacts:
    when: always
    paths:
      - coverage/
    expire_in: 1 week
  script:
    - pnpm i
    - pnpm run lint
    - pnpm run build
    - pnpm run test:cov-html
