export enum AppointmentType {
  weFe = 'Weihnachtsferien',
  heFe = 'Herbstferien',
  soFe = 'Sommerferien',
  osFe = 'Osterferien',
  nj = 'Neujahr',
  vt = 'Valentinstag',
  tda = 'Tag der Arbeit',
  tdde = 'Tag der dt. Einheit',
  nik = 'Nikolaus',
  ha = 'Heiligabend',
  wei1 = '1. Weihnachtsfeiertag',
  wei2 = '2. Weihnachtsfeiertag',
  sil = 'Silvester',
  rm = 'Rosenmontag',
  fn = 'Fastnacht',
  am = 'Aschermittwoch',
  kf = 'Karfreitag',
  os = 'Ostersonntag',
  om = 'Ostermontag',
  ch = 'Christi Himmelfahrt',
  ps = 'Pfingststonntag',
  pm = 'Pfingstmontag',
  fl = 'Fronleichnam',
  mu = 'Muttertag',
  adv1 = '1. Advent',
  adv2 = '2. Advent',
  adv3 = '3. Advent',
  adv4 = '4. Advent',
  tso = 'Totensonntag',
}

export type AppointmentTypeKey = keyof typeof AppointmentType
